// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef _ESP32S3ENTERTAINMENTDISPLAY_UI_H
#define _ESP32S3ENTERTAINMENTDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Music_Screen.h"
#include "screens/ui_Discord_Screen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * VolumeFadeIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * VolumeFadeOut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MovePopoutMenu_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MovePopoutMenuReverse_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScreenSwitchAnimation_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_backbutton_png);    // assets/backbutton.png
LV_IMG_DECLARE(ui_img_1518759221);    // assets/play-button-round-white-icon.png
LV_IMG_DECLARE(ui_img_2115154753);    // assets/pause-button-round-white-icon.png
LV_IMG_DECLARE(ui_img_nextbutton_png);    // assets/nextbutton.png
LV_IMG_DECLARE(ui_img_anim_25_png);    // assets/anim_25.png
LV_IMG_DECLARE(ui_img_2111856141);    // assets/popup-shape.png
LV_IMG_DECLARE(ui_img_1902415918);    // assets/Chevron-Icon-White.png
LV_IMG_DECLARE(ui_img_231780434);    // assets/Discord-Symbol-White.png
LV_IMG_DECLARE(ui_img_micnomutemini_png);    // assets/MicNoMutemini.png
LV_IMG_DECLARE(ui_img_micmutedmini_png);    // assets/MicMutedmini.png
LV_IMG_DECLARE(ui_img_headphonesnodeafenmini_png);    // assets/HeadphonesNoDeafenmini.png
LV_IMG_DECLARE(ui_img_headphonesdeafenedmini_png);    // assets/HeadphonesDeafenedmini.png
LV_IMG_DECLARE(ui_img_endcallnotogglemini_png);    // assets/EndCallNoTogglemini.png
LV_IMG_DECLARE(ui_img_endcallleftmini_png);    // assets/EndCallLeftmini.png
LV_IMG_DECLARE(ui_img_backbuttonmini_png);    // assets/backbuttonmini.png
LV_IMG_DECLARE(ui_img_378055568);    // assets/play-button-round-white-iconmini.png
LV_IMG_DECLARE(ui_img_1909143296);    // assets/pause-button-round-white-iconmini.png
LV_IMG_DECLARE(ui_img_nextbuttonmini_png);    // assets/nextbuttonmini.png
LV_IMG_DECLARE(ui_img_1771568924);    // assets/icons8-music-64.png
LV_IMG_DECLARE(ui_img_micnomute_png);    // assets/MicNoMute.png
LV_IMG_DECLARE(ui_img_micmuted_png);    // assets/MicMuted.png
LV_IMG_DECLARE(ui_img_headphonesnodeafen_png);    // assets/HeadphonesNoDeafen.png
LV_IMG_DECLARE(ui_img_headphonesdeafened_png);    // assets/HeadphonesDeafened.png
LV_IMG_DECLARE(ui_img_endcallnotoggle_png);    // assets/EndCallNoToggle.png
LV_IMG_DECLARE(ui_img_endcallleft_png);    // assets/EndCallLeft.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
