// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#include "ui.h"
#include "music_player_logic.h"
#include "Arduino.h"
extern bool is_playing;
extern bool user_is_seeking;
extern void sync_play_pause_visuals();
uint32_t seek_lockout_timer = 0;



void init_media_player_cb(lv_event_t * e)
{
	// Your code here
}


static void scale_anim_cb(void * var, int32_t v) {
    lv_obj_t * obj = (lv_obj_t *)var;
    lv_obj_set_style_transform_scale(obj, v, LV_PART_MAIN);
}
 
void trigger_button_pop(lv_event_t * e) {
    
    lv_obj_t * btn = (lv_obj_t *)lv_event_get_target(e);
    if (!btn) return;

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, btn);
    lv_anim_set_values(&a, 256, 220);       
    lv_anim_set_time(&a, 100);            
    lv_anim_set_playback_time(&a, 100);     
    lv_anim_set_exec_cb(&a, scale_anim_cb);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_start(&a);
}

void track_slider_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
       user_is_seeking = true;
    }
    else if(event_code == LV_EVENT_RELEASED || event_code == LV_EVENT_PRESS_LOST) {
        user_is_seeking = false;
        
        int slider_value = lv_slider_get_value(ui_SongPositionSlider);
        current_player_state.position_seconds = slider_value;
        
        
        seek_lockout_timer = millis();
        
        Serial.print("CMD:SEEK:");
        Serial.println(slider_value);
    }
}

void prev_song_cb(lv_event_t * e)
{
    trigger_button_pop(e);
	Serial.println("CMD:PREV");
    
}

void play_pause_toggle_cb(lv_event_t * e)
{
    Serial.println("CMD:TOGGLE");
    
	current_player_state.is_playing = !current_player_state.is_playing;
    sync_play_pause_visuals();
}

void next_song_cb(lv_event_t * e)
{
    trigger_button_pop(e);
	Serial.println("CMD:NEXT");
}


 
void toggle_mute(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_CLICKED) {
        Serial.println("CMD:TOGGLE_MUTE");
    }
}

void toggle_deafen(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_CLICKED) {
        Serial.println("CMD:TOGGLE_DEAFEN");
    }
}

void lv_disc_call(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_RELEASED) {
        Serial.println("CMD:LV_CALL");
    }
}

// --- SCREEN SWITCHING WITH FADE ANIMATION ---

void switch_to_discord_screen(lv_event_t * e) {
    // Crossfade to Discord screen over 300ms
    lv_screen_load_anim(ui_Discord_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, false);
}

void switch_to_music_screen(lv_event_t * e) {
    // Crossfade back to Music screen over 300ms
    lv_screen_load_anim(ui_Music_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, false);
}

void register_screen_switch_handlers(void) {
    // Bind the Music screen's Discord Icon
    if (ui_DiscordIcon != NULL) {
        lv_obj_add_event_cb(ui_DiscordIcon, switch_to_discord_screen, LV_EVENT_CLICKED, NULL);
    }
    
    // Bind the Discord screen's Music Icon
    if (ui_MusicIcon != NULL) {
        lv_obj_add_event_cb(ui_MusicIcon, switch_to_music_screen, LV_EVENT_CLICKED, NULL);
    }
}