// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void init_media_player_cb(lv_event_t * e);
void track_slider_cb(lv_event_t * e);
void prev_song_cb(lv_event_t * e);
void play_pause_toggle_cb(lv_event_t * e);
void next_song_cb(lv_event_t * e);
void toggle_mute(lv_event_t * e);
void toggle_deafen(lv_event_t * e);
void lv_disc_call(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
