// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#include "../ui.h"

lv_obj_t * ui_Discord_Screen = NULL;
lv_obj_t * ui_PopoutMenuContainer2 = NULL;
lv_obj_t * ui_PopoutMenuButton2 = NULL;
lv_obj_t * ui_SongButtons2 = NULL;
lv_obj_t * ui_BackButton3 = NULL;
lv_obj_t * ui_PlayPauseButton3 = NULL;
lv_obj_t * ui_NextButton2 = NULL;
lv_obj_t * ui_Song_Name2 = NULL;
lv_obj_t * ui_Button_Container2 = NULL;
lv_obj_t * ui_MusicIcon = NULL;
lv_obj_t * ui_ControlPanel = NULL;
lv_obj_t * ui_MuteButton = NULL;
lv_obj_t * ui_PanelGap1 = NULL;
lv_obj_t * ui_DeafenButton = NULL;
lv_obj_t * ui_PanelGap2 = NULL;
lv_obj_t * ui_LeaveCallButton = NULL;
lv_obj_t * ui_DiscordBackground = NULL;
lv_obj_t * ui_DiscordInfo = NULL;
// event funtions
void ui_event_PopoutMenuButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MovePopoutMenu_Animation(ui_PopoutMenuContainer2, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MovePopoutMenuReverse_Animation(ui_PopoutMenuContainer2, 0);
    }
}

void ui_event_BackButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        prev_song_cb(e);
    }
}

void ui_event_PlayPauseButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        play_pause_toggle_cb(e);
    }
}

void ui_event_NextButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        next_song_cb(e);
    }
}

void ui_event_MuteButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggle_mute(e);
    }
}

void ui_event_DeafenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggle_deafen(e);
    }
}

void ui_event_LeaveCallButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        lv_disc_call(e);
    }
}

// build funtions

void ui_Discord_Screen_screen_init(void)
{
    ui_Discord_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Discord_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PopoutMenuContainer2 = lv_obj_create(ui_Discord_Screen);
    lv_obj_remove_style_all(ui_PopoutMenuContainer2);
    lv_obj_set_width(ui_PopoutMenuContainer2, 623);
    lv_obj_set_height(ui_PopoutMenuContainer2, 80);
    lv_obj_set_x(ui_PopoutMenuContainer2, -37);
    lv_obj_set_y(ui_PopoutMenuContainer2, 195);
    lv_obj_set_align(ui_PopoutMenuContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PopoutMenuContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_PopoutMenuContainer2, &ui_img_2111856141, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PopoutMenuContainer2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PopoutMenuContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PopoutMenuContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PopoutMenuContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PopoutMenuContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopoutMenuButton2 = lv_imagebutton_create(ui_PopoutMenuContainer2);
    lv_imagebutton_set_src(ui_PopoutMenuButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_1902415918, NULL);
    lv_obj_set_width(ui_PopoutMenuButton2, 48);
    lv_obj_set_height(ui_PopoutMenuButton2, 26);
    lv_obj_set_x(ui_PopoutMenuButton2, -281);
    lv_obj_set_y(ui_PopoutMenuButton2, -25);
    lv_obj_set_align(ui_PopoutMenuButton2, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_PopoutMenuButton2, 4);
    lv_obj_add_flag(ui_PopoutMenuButton2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_opa(ui_PopoutMenuButton2, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongButtons2 = lv_obj_create(ui_PopoutMenuContainer2);
    lv_obj_remove_style_all(ui_SongButtons2);
    lv_obj_set_width(ui_SongButtons2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_SongButtons2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_SongButtons2, 60);
    lv_obj_set_y(ui_SongButtons2, 16);
    lv_obj_set_align(ui_SongButtons2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongButtons2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SongButtons2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SongButtons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButton3 = lv_imagebutton_create(ui_SongButtons2);
    lv_imagebutton_set_src(ui_BackButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backbuttonmini_png, NULL);
    lv_obj_set_height(ui_BackButton3, 48);
    lv_obj_set_width(ui_BackButton3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_align(ui_BackButton3, LV_ALIGN_CENTER);

    ui_PlayPauseButton3 = lv_imagebutton_create(ui_SongButtons2);
    lv_imagebutton_set_src(ui_PlayPauseButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_378055568, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1909143296, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton3, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_378055568, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton3, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_1909143296, NULL);
    lv_obj_set_height(ui_PlayPauseButton3, 48);
    lv_obj_set_width(ui_PlayPauseButton3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_x(ui_PlayPauseButton3, -1);
    lv_obj_set_y(ui_PlayPauseButton3, -2);
    lv_obj_set_align(ui_PlayPauseButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayPauseButton3, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_NextButton2 = lv_imagebutton_create(ui_SongButtons2);
    lv_imagebutton_set_src(ui_NextButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_nextbuttonmini_png, NULL);
    lv_obj_set_height(ui_NextButton2, 48);
    lv_obj_set_width(ui_NextButton2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_align(ui_NextButton2, LV_ALIGN_CENTER);

    ui_Song_Name2 = lv_label_create(ui_SongButtons2);
    lv_obj_set_width(ui_Song_Name2, 321);
    lv_obj_set_height(ui_Song_Name2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Song_Name2, -22);
    lv_obj_set_y(ui_Song_Name2, -23);
    lv_obj_set_align(ui_Song_Name2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Song_Name2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Song_Name2, "Awaiting Connection...");
    lv_obj_set_scrollbar_mode(ui_Song_Name2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Song_Name2, LV_DIR_TOP);
    lv_obj_set_style_text_font(ui_Song_Name2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Song_Name2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Song_Name2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Song_Name2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Song_Name2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Container2 = lv_obj_create(ui_PopoutMenuContainer2);
    lv_obj_remove_style_all(ui_Button_Container2);
    lv_obj_set_height(ui_Button_Container2, 44);
    lv_obj_set_width(ui_Button_Container2, LV_SIZE_CONTENT);   /// 123
    lv_obj_set_x(ui_Button_Container2, -220);
    lv_obj_set_y(ui_Button_Container2, 15);
    lv_obj_set_align(ui_Button_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MusicIcon = lv_imagebutton_create(ui_Button_Container2);
    lv_imagebutton_set_src(ui_MusicIcon, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1771568924, NULL);
    lv_imagebutton_set_src(ui_MusicIcon, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1771568924, NULL);
    lv_obj_set_width(ui_MusicIcon, 48);
    lv_obj_set_height(ui_MusicIcon, 48);
    lv_obj_set_x(ui_MusicIcon, -225);
    lv_obj_set_y(ui_MusicIcon, 16);
    lv_obj_set_align(ui_MusicIcon, LV_ALIGN_CENTER);

    ui_ControlPanel = lv_obj_create(ui_Discord_Screen);
    lv_obj_set_width(ui_ControlPanel, 100);
    lv_obj_set_height(ui_ControlPanel, 290);
    lv_obj_set_x(ui_ControlPanel, -314);
    lv_obj_set_y(ui_ControlPanel, -34);
    lv_obj_set_align(ui_ControlPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ControlPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ControlPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_ControlPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MuteButton = lv_imagebutton_create(ui_ControlPanel);
    lv_imagebutton_set_src(ui_MuteButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_micnomute_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_micnomute_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_micmuted_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_micmuted_png, NULL);
    lv_obj_set_width(ui_MuteButton, 64);
    lv_obj_set_height(ui_MuteButton, 64);
    lv_obj_set_x(ui_MuteButton, -313);
    lv_obj_set_y(ui_MuteButton, -96);
    lv_obj_set_align(ui_MuteButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MuteButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_MuteButton, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_radius(ui_MuteButton, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_MuteButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MuteButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_MuteButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_MuteButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_MuteButton, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_MuteButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_MuteButton, 10, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_PanelGap1 = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_PanelGap1, 100);
    lv_obj_set_height(ui_PanelGap1, 5);
    lv_obj_set_align(ui_PanelGap1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelGap1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_PanelGap1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeafenButton = lv_imagebutton_create(ui_ControlPanel);
    lv_imagebutton_set_src(ui_DeafenButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_headphonesnodeafen_png, NULL);
    lv_imagebutton_set_src(ui_DeafenButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_headphonesnodeafen_png, NULL);
    lv_imagebutton_set_src(ui_DeafenButton, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_headphonesdeafened_png,
                           NULL);
    lv_imagebutton_set_src(ui_DeafenButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_headphonesdeafened_png,
                           NULL);
    lv_obj_set_width(ui_DeafenButton, 64);
    lv_obj_set_height(ui_DeafenButton, 64);
    lv_obj_set_x(ui_DeafenButton, -313);
    lv_obj_set_y(ui_DeafenButton, -9);
    lv_obj_set_align(ui_DeafenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeafenButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_DeafenButton, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_DeafenButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DeafenButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_DeafenButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_DeafenButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_DeafenButton, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_DeafenButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelGap2 = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_PanelGap2, 100);
    lv_obj_set_height(ui_PanelGap2, 5);
    lv_obj_set_align(ui_PanelGap2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelGap2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_PanelGap2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeaveCallButton = lv_imagebutton_create(ui_ControlPanel);
    lv_imagebutton_set_src(ui_LeaveCallButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_endcallnotoggle_png, NULL);
    lv_imagebutton_set_src(ui_LeaveCallButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_endcallleft_png, NULL);
    lv_obj_set_width(ui_LeaveCallButton, 64);
    lv_obj_set_height(ui_LeaveCallButton, 64);
    lv_obj_set_x(ui_LeaveCallButton, -303);
    lv_obj_set_y(ui_LeaveCallButton, 102);
    lv_obj_set_align(ui_LeaveCallButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_LeaveCallButton, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_LeaveCallButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LeaveCallButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_LeaveCallButton, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_LeaveCallButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_LeaveCallButton, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_LeaveCallButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DiscordBackground = lv_obj_create(ui_Discord_Screen);
    lv_obj_set_width(ui_DiscordBackground, 550);
    lv_obj_set_height(ui_DiscordBackground, 350);
    lv_obj_set_x(ui_DiscordBackground, 45);
    lv_obj_set_y(ui_DiscordBackground, -28);
    lv_obj_set_align(ui_DiscordBackground, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DiscordBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DiscordInfo = lv_obj_create(ui_DiscordBackground);
    lv_obj_remove_style_all(ui_DiscordInfo);
    lv_obj_set_width(ui_DiscordInfo, 535);
    lv_obj_set_height(ui_DiscordInfo, 340);
    lv_obj_set_align(ui_DiscordInfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DiscordInfo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_DiscordInfo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_DiscordInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_DiscordInfo, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DiscordInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DiscordInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DiscordInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DiscordInfo, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DiscordInfo, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PopoutMenuButton2, ui_event_PopoutMenuButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton3, ui_event_BackButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayPauseButton3, ui_event_PlayPauseButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton2, ui_event_NextButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MuteButton, ui_event_MuteButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeafenButton, ui_event_DeafenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LeaveCallButton, ui_event_LeaveCallButton, LV_EVENT_ALL, NULL);

}

void ui_Discord_Screen_screen_destroy(void)
{
    if(ui_Discord_Screen) lv_obj_del(ui_Discord_Screen);

    // NULL screen variables
    ui_Discord_Screen = NULL;
    ui_PopoutMenuContainer2 = NULL;
    ui_PopoutMenuButton2 = NULL;
    ui_SongButtons2 = NULL;
    ui_BackButton3 = NULL;
    ui_PlayPauseButton3 = NULL;
    ui_NextButton2 = NULL;
    ui_Song_Name2 = NULL;
    ui_Button_Container2 = NULL;
    ui_MusicIcon = NULL;
    ui_ControlPanel = NULL;
    ui_MuteButton = NULL;
    ui_PanelGap1 = NULL;
    ui_DeafenButton = NULL;
    ui_PanelGap2 = NULL;
    ui_LeaveCallButton = NULL;
    ui_DiscordBackground = NULL;
    ui_DiscordInfo = NULL;

}
