// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef UI_DISCORD_SCREEN_H
#define UI_DISCORD_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Discord_Screen
extern void ui_Discord_Screen_screen_init(void);
extern void ui_Discord_Screen_screen_destroy(void);
extern lv_obj_t * ui_Discord_Screen;
extern lv_obj_t * ui_PopoutMenuContainer2;
extern void ui_event_PopoutMenuButton2(lv_event_t * e);
extern lv_obj_t * ui_PopoutMenuButton2;
extern lv_obj_t * ui_SongButtons2;
extern void ui_event_BackButton3(lv_event_t * e);
extern lv_obj_t * ui_BackButton3;
extern void ui_event_PlayPauseButton3(lv_event_t * e);
extern lv_obj_t * ui_PlayPauseButton3;
extern void ui_event_NextButton2(lv_event_t * e);
extern lv_obj_t * ui_NextButton2;
extern lv_obj_t * ui_Song_Name2;
extern lv_obj_t * ui_Button_Container2;
extern lv_obj_t * ui_MusicIcon;
extern lv_obj_t * ui_ControlPanel;
extern void ui_event_MuteButton(lv_event_t * e);
extern lv_obj_t * ui_MuteButton;
extern lv_obj_t * ui_PanelGap1;
extern void ui_event_DeafenButton(lv_event_t * e);
extern lv_obj_t * ui_DeafenButton;
extern lv_obj_t * ui_PanelGap2;
extern void ui_event_LeaveCallButton(lv_event_t * e);
extern lv_obj_t * ui_LeaveCallButton;
extern lv_obj_t * ui_DiscordBackground;
extern lv_obj_t * ui_DiscordInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

