// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#include "../ui.h"

lv_obj_t * ui_Music_Screen = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_Volume_Panel = NULL;
lv_obj_t * ui_uiForVolumePopout = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Vol_Percent = NULL;
lv_obj_t * ui_SongInformationAndPlayback = NULL;
lv_obj_t * ui_Song_Name = NULL;
lv_obj_t * ui_Artist_Name = NULL;
lv_obj_t * ui_SongPositionSlider = NULL;
lv_obj_t * ui_CurrentTimeAndTotalTime = NULL;
lv_obj_t * ui_Current_Time_T1 = NULL;
lv_obj_t * ui_Total_Time_T2 = NULL;
lv_obj_t * ui_SongButtons = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_PlayPauseButton = NULL;
lv_obj_t * ui_NextButton = NULL;
lv_obj_t * ui_AlbumCoverContainer = NULL;
lv_obj_t * ui_SongImage = NULL;
lv_obj_t * ui_PopoutMenuContainer = NULL;
lv_obj_t * ui_PopoutMenuButton = NULL;
lv_obj_t * ui_Button_Container = NULL;
lv_obj_t * ui_DiscordIcon = NULL;
lv_obj_t * ui_SongButtons3 = NULL;
lv_obj_t * ui_MuteButton2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_DeafenButton2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_LeaveCallButton2 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Voice_Chat_Name = NULL;
// event funtions
void ui_event_Music_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        init_media_player_cb(e);
    }
}

void ui_event_Volume_Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        VolumeFadeIn_Animation(ui_Volume_Panel, 0);
    }
    if(event_code == LV_EVENT_READY) {
        VolumeFadeOut_Animation(ui_Volume_Panel, 2000);
    }
}

void ui_event_SongPositionSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        track_slider_cb(e);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        prev_song_cb(e);
    }
}

void ui_event_PlayPauseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        play_pause_toggle_cb(e);
    }
}

void ui_event_NextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        next_song_cb(e);
    }
}

void ui_event_PopoutMenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MovePopoutMenu_Animation(ui_PopoutMenuContainer, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        MovePopoutMenuReverse_Animation(ui_PopoutMenuContainer, 0);
    }
}

void ui_event_MuteButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggle_mute(e);
    }
}

void ui_event_DeafenButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggle_deafen(e);
    }
}

void ui_event_LeaveCallButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        lv_disc_call(e);
    }
}

// build funtions

void ui_Music_Screen_screen_init(void)
{
    ui_Music_Screen = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Music_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Music_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_clip_corner(ui_Music_Screen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_Music_Screen);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, -347);
    lv_obj_set_y(ui_TimeLabel, -219);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Volume_Panel = lv_obj_create(ui_Music_Screen);
    lv_obj_set_width(ui_Volume_Panel, 40);
    lv_obj_set_height(ui_Volume_Panel, 405);
    lv_obj_set_x(ui_Volume_Panel, 369);
    lv_obj_set_y(ui_Volume_Panel, -8);
    lv_obj_set_align(ui_Volume_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Volume_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiForVolumePopout = lv_obj_create(ui_Volume_Panel);
    lv_obj_remove_style_all(ui_uiForVolumePopout);
    lv_obj_set_width(ui_uiForVolumePopout, 35);
    lv_obj_set_height(ui_uiForVolumePopout, 466);
    lv_obj_set_x(ui_uiForVolumePopout, -1);
    lv_obj_set_y(ui_uiForVolumePopout, 3);
    lv_obj_set_align(ui_uiForVolumePopout, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiForVolumePopout, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiForVolumePopout, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_uiForVolumePopout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_uiForVolumePopout, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiForVolumePopout, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiForVolumePopout, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiForVolumePopout, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_uiForVolumePopout);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 21);
    lv_obj_set_height(ui_Bar1, 344);
    lv_obj_set_x(ui_Bar1, -30);
    lv_obj_set_y(ui_Bar1, -1);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Vol_Percent = lv_label_create(ui_uiForVolumePopout);
    lv_obj_set_width(ui_Vol_Percent, 40);
    lv_obj_set_height(ui_Vol_Percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Vol_Percent, 0);
    lv_obj_set_y(ui_Vol_Percent, 3);
    lv_obj_set_align(ui_Vol_Percent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Vol_Percent, "100%");
    lv_obj_set_style_pad_left(ui_Vol_Percent, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Vol_Percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Vol_Percent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Vol_Percent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongInformationAndPlayback = lv_obj_create(ui_Music_Screen);
    lv_obj_remove_style_all(ui_SongInformationAndPlayback);
    lv_obj_set_width(ui_SongInformationAndPlayback, 420);
    lv_obj_set_height(ui_SongInformationAndPlayback, LV_SIZE_CONTENT);    /// 190
    lv_obj_set_x(ui_SongInformationAndPlayback, 148);
    lv_obj_set_y(ui_SongInformationAndPlayback, -11);
    lv_obj_set_align(ui_SongInformationAndPlayback, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongInformationAndPlayback, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SongInformationAndPlayback, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SongInformationAndPlayback, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Song_Name = lv_label_create(ui_SongInformationAndPlayback);
    lv_obj_set_width(ui_Song_Name, 379);
    lv_obj_set_height(ui_Song_Name, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Song_Name, 0);
    lv_obj_set_y(ui_Song_Name, -46);
    lv_obj_set_align(ui_Song_Name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Song_Name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Song_Name, "Awaiting Connection...");
    lv_obj_set_scrollbar_mode(ui_Song_Name, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Song_Name, LV_DIR_TOP);
    lv_obj_set_style_text_font(ui_Song_Name, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Song_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Song_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Song_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Song_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Artist_Name = lv_label_create(ui_SongInformationAndPlayback);
    lv_obj_set_width(ui_Artist_Name, 380);
    lv_obj_set_height(ui_Artist_Name, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Artist_Name, 46);
    lv_obj_set_y(ui_Artist_Name, 13);
    lv_obj_set_align(ui_Artist_Name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Artist_Name, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Artist_Name, "Artist Name");
    lv_obj_set_style_text_font(ui_Artist_Name, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Artist_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Artist_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Artist_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Artist_Name, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongPositionSlider = lv_slider_create(ui_SongInformationAndPlayback);
    lv_slider_set_value(ui_SongPositionSlider, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SongPositionSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SongPositionSlider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_SongPositionSlider, 400);
    lv_obj_set_height(ui_SongPositionSlider, 15);
    lv_obj_set_x(ui_SongPositionSlider, -36);
    lv_obj_set_y(ui_SongPositionSlider, 29);
    lv_obj_set_align(ui_SongPositionSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SongPositionSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongPositionSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SongPositionSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongPositionSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SongPositionSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SongPositionSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SongPositionSlider,
                                                                                                         lv_obj_get_style_pad_right(ui_SongPositionSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_CurrentTimeAndTotalTime = lv_obj_create(ui_SongInformationAndPlayback);
    lv_obj_remove_style_all(ui_CurrentTimeAndTotalTime);
    lv_obj_set_width(ui_CurrentTimeAndTotalTime, 390);
    lv_obj_set_height(ui_CurrentTimeAndTotalTime, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_CurrentTimeAndTotalTime, 31);
    lv_obj_set_y(ui_CurrentTimeAndTotalTime, 54);
    lv_obj_set_align(ui_CurrentTimeAndTotalTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentTimeAndTotalTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentTimeAndTotalTime, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_CurrentTimeAndTotalTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_CurrentTimeAndTotalTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentTimeAndTotalTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentTimeAndTotalTime, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentTimeAndTotalTime, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Current_Time_T1 = lv_label_create(ui_CurrentTimeAndTotalTime);
    lv_obj_set_width(ui_Current_Time_T1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Current_Time_T1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Current_Time_T1, -4);
    lv_obj_set_y(ui_Current_Time_T1, 27);
    lv_obj_set_align(ui_Current_Time_T1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Current_Time_T1, "0:00");
    lv_obj_set_style_pad_left(ui_Current_Time_T1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Current_Time_T1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Current_Time_T1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Current_Time_T1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Total_Time_T2 = lv_label_create(ui_CurrentTimeAndTotalTime);
    lv_obj_set_width(ui_Total_Time_T2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Total_Time_T2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Total_Time_T2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Total_Time_T2, "99:99");
    lv_obj_set_style_pad_left(ui_Total_Time_T2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Total_Time_T2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Total_Time_T2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Total_Time_T2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongButtons = lv_obj_create(ui_Music_Screen);
    lv_obj_remove_style_all(ui_SongButtons);
    lv_obj_set_width(ui_SongButtons, 200);
    lv_obj_set_height(ui_SongButtons, 80);
    lv_obj_set_x(ui_SongButtons, 174);
    lv_obj_set_y(ui_SongButtons, 91);
    lv_obj_set_align(ui_SongButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SongButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SongButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButton = lv_imagebutton_create(ui_SongButtons);
    lv_imagebutton_set_src(ui_BackButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backbutton_png, NULL);
    lv_obj_set_width(ui_BackButton, 64);
    lv_obj_set_height(ui_BackButton, 64);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);

    ui_PlayPauseButton = lv_imagebutton_create(ui_SongButtons);
    lv_imagebutton_set_src(ui_PlayPauseButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1518759221, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_2115154753, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_1518759221, NULL);
    lv_imagebutton_set_src(ui_PlayPauseButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_2115154753, NULL);
    lv_obj_set_width(ui_PlayPauseButton, 64);
    lv_obj_set_height(ui_PlayPauseButton, 64);
    lv_obj_set_align(ui_PlayPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayPauseButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_NextButton = lv_imagebutton_create(ui_SongButtons);
    lv_imagebutton_set_src(ui_NextButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_nextbutton_png, NULL);
    lv_obj_set_width(ui_NextButton, 64);
    lv_obj_set_height(ui_NextButton, 64);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);

    ui_AlbumCoverContainer = lv_obj_create(ui_Music_Screen);
    lv_obj_remove_style_all(ui_AlbumCoverContainer);
    lv_obj_set_width(ui_AlbumCoverContainer, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_AlbumCoverContainer, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_AlbumCoverContainer, -228);
    lv_obj_set_y(ui_AlbumCoverContainer, -1);
    lv_obj_set_align(ui_AlbumCoverContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AlbumCoverContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AlbumCoverContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_AlbumCoverContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlbumCoverContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_AlbumCoverContainer, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_AlbumCoverContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AlbumCoverContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AlbumCoverContainer, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlbumCoverContainer, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SongImage = lv_image_create(ui_AlbumCoverContainer);
    lv_image_set_src(ui_SongImage, &ui_img_anim_25_png);
    lv_obj_set_width(ui_SongImage, 250);
    lv_obj_set_height(ui_SongImage, 250);
    lv_obj_set_x(ui_SongImage, -80);
    lv_obj_set_y(ui_SongImage, -6);
    lv_obj_set_align(ui_SongImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SongImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SongImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SongImage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SongImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SongImage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SongImage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopoutMenuContainer = lv_obj_create(ui_Music_Screen);
    lv_obj_remove_style_all(ui_PopoutMenuContainer);
    lv_obj_set_width(ui_PopoutMenuContainer, 623);
    lv_obj_set_height(ui_PopoutMenuContainer, 80);
    lv_obj_set_x(ui_PopoutMenuContainer, -37);
    lv_obj_set_y(ui_PopoutMenuContainer, 195);
    lv_obj_set_align(ui_PopoutMenuContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PopoutMenuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_PopoutMenuContainer, &ui_img_2111856141, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PopoutMenuContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PopoutMenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PopoutMenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PopoutMenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PopoutMenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopoutMenuButton = lv_imagebutton_create(ui_PopoutMenuContainer);
    lv_imagebutton_set_src(ui_PopoutMenuButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_1902415918, NULL);
    lv_imagebutton_set_src(ui_PopoutMenuButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_1902415918, NULL);
    lv_obj_set_width(ui_PopoutMenuButton, 48);
    lv_obj_set_height(ui_PopoutMenuButton, 26);
    lv_obj_set_x(ui_PopoutMenuButton, -281);
    lv_obj_set_y(ui_PopoutMenuButton, -25);
    lv_obj_set_align(ui_PopoutMenuButton, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_PopoutMenuButton, 4);
    lv_obj_add_flag(ui_PopoutMenuButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_opa(ui_PopoutMenuButton, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Container = lv_obj_create(ui_PopoutMenuContainer);
    lv_obj_remove_style_all(ui_Button_Container);
    lv_obj_set_height(ui_Button_Container, 44);
    lv_obj_set_width(ui_Button_Container, LV_SIZE_CONTENT);   /// 132
    lv_obj_set_x(ui_Button_Container, -220);
    lv_obj_set_y(ui_Button_Container, 15);
    lv_obj_set_align(ui_Button_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button_Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DiscordIcon = lv_imagebutton_create(ui_Button_Container);
    lv_imagebutton_set_src(ui_DiscordIcon, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_231780434, NULL);
    lv_imagebutton_set_src(ui_DiscordIcon, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_231780434, NULL);
    lv_imagebutton_set_src(ui_DiscordIcon, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_231780434, NULL);
    lv_imagebutton_set_src(ui_DiscordIcon, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_231780434, NULL);
    lv_obj_set_width(ui_DiscordIcon, 48);
    lv_obj_set_height(ui_DiscordIcon, 36);
    lv_obj_set_x(ui_DiscordIcon, -225);
    lv_obj_set_y(ui_DiscordIcon, 16);
    lv_obj_set_align(ui_DiscordIcon, LV_ALIGN_CENTER);

    ui_SongButtons3 = lv_obj_create(ui_PopoutMenuContainer);
    lv_obj_remove_style_all(ui_SongButtons3);
    lv_obj_set_width(ui_SongButtons3, 489);
    lv_obj_set_height(ui_SongButtons3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_SongButtons3, 69);
    lv_obj_set_y(ui_SongButtons3, 16);
    lv_obj_set_align(ui_SongButtons3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongButtons3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SongButtons3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SongButtons3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MuteButton2 = lv_imagebutton_create(ui_SongButtons3);
    lv_imagebutton_set_src(ui_MuteButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_micnomutemini_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_micmutedmini_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_micmutedmini_png, NULL);
    lv_imagebutton_set_src(ui_MuteButton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_micmutedmini_png, NULL);
    lv_obj_set_width(ui_MuteButton2, 48);
    lv_obj_set_height(ui_MuteButton2, 48);
    lv_obj_set_x(ui_MuteButton2, -313);
    lv_obj_set_y(ui_MuteButton2, -96);
    lv_obj_set_align(ui_MuteButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MuteButton2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_MuteButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MuteButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_MuteButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_MuteButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_MuteButton2, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_MuteButton2, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_MuteButton2, 10, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Panel2 = lv_obj_create(ui_SongButtons3);
    lv_obj_set_width(ui_Panel2, 10);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeafenButton2 = lv_imagebutton_create(ui_SongButtons3);
    lv_imagebutton_set_src(ui_DeafenButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_headphonesnodeafenmini_png, NULL);
    lv_imagebutton_set_src(ui_DeafenButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_headphonesdeafenedmini_png, NULL);
    lv_imagebutton_set_src(ui_DeafenButton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_headphonesdeafenedmini_png,
                           NULL);
    lv_imagebutton_set_src(ui_DeafenButton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL,
                           &ui_img_headphonesdeafenedmini_png, NULL);
    lv_obj_set_height(ui_DeafenButton2, 48);
    lv_obj_set_width(ui_DeafenButton2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_x(ui_DeafenButton2, -313);
    lv_obj_set_y(ui_DeafenButton2, -9);
    lv_obj_set_align(ui_DeafenButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_DeafenButton2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_DeafenButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DeafenButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_DeafenButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_DeafenButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_DeafenButton2, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_DeafenButton2, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel1 = lv_obj_create(ui_SongButtons3);
    lv_obj_set_width(ui_Panel1, 10);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeaveCallButton2 = lv_imagebutton_create(ui_SongButtons3);
    lv_imagebutton_set_src(ui_LeaveCallButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_endcallnotogglemini_png, NULL);
    lv_imagebutton_set_src(ui_LeaveCallButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_endcallleftmini_png, NULL);
    lv_obj_set_height(ui_LeaveCallButton2, 48);
    lv_obj_set_width(ui_LeaveCallButton2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_x(ui_LeaveCallButton2, -303);
    lv_obj_set_y(ui_LeaveCallButton2, 102);
    lv_obj_set_align(ui_LeaveCallButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_LeaveCallButton2, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_LeaveCallButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LeaveCallButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_LeaveCallButton2, lv_color_hex(0x832D2D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_LeaveCallButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_LeaveCallButton2, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_LeaveCallButton2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel4 = lv_obj_create(ui_SongButtons3);
    lv_obj_set_width(ui_Panel4, 10);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voice_Chat_Name = lv_label_create(ui_SongButtons3);
    lv_obj_set_width(ui_Voice_Chat_Name, 299);
    lv_obj_set_height(ui_Voice_Chat_Name, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Voice_Chat_Name, -9);
    lv_obj_set_y(ui_Voice_Chat_Name, -25);
    lv_obj_set_align(ui_Voice_Chat_Name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Voice_Chat_Name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Voice_Chat_Name, "");
    lv_obj_set_scrollbar_mode(ui_Voice_Chat_Name, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Voice_Chat_Name, LV_DIR_TOP);
    lv_obj_set_style_text_align(ui_Voice_Chat_Name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Voice_Chat_Name, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Voice_Chat_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Voice_Chat_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Voice_Chat_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Voice_Chat_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Volume_Panel, ui_event_Volume_Panel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SongPositionSlider, ui_event_SongPositionSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayPauseButton, ui_event_PlayPauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PopoutMenuButton, ui_event_PopoutMenuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MuteButton2, ui_event_MuteButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeafenButton2, ui_event_DeafenButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LeaveCallButton2, ui_event_LeaveCallButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Music_Screen, ui_event_Music_Screen, LV_EVENT_ALL, NULL);

}

void ui_Music_Screen_screen_destroy(void)
{
    if(ui_Music_Screen) lv_obj_del(ui_Music_Screen);

    // NULL screen variables
    ui_Music_Screen = NULL;
    ui_TimeLabel = NULL;
    ui_Volume_Panel = NULL;
    ui_uiForVolumePopout = NULL;
    ui_Bar1 = NULL;
    ui_Vol_Percent = NULL;
    ui_SongInformationAndPlayback = NULL;
    ui_Song_Name = NULL;
    ui_Artist_Name = NULL;
    ui_SongPositionSlider = NULL;
    ui_CurrentTimeAndTotalTime = NULL;
    ui_Current_Time_T1 = NULL;
    ui_Total_Time_T2 = NULL;
    ui_SongButtons = NULL;
    ui_BackButton = NULL;
    ui_PlayPauseButton = NULL;
    ui_NextButton = NULL;
    ui_AlbumCoverContainer = NULL;
    ui_SongImage = NULL;
    ui_PopoutMenuContainer = NULL;
    ui_PopoutMenuButton = NULL;
    ui_Button_Container = NULL;
    ui_DiscordIcon = NULL;
    ui_SongButtons3 = NULL;
    ui_MuteButton2 = NULL;
    ui_Panel2 = NULL;
    ui_DeafenButton2 = NULL;
    ui_Panel1 = NULL;
    ui_LeaveCallButton2 = NULL;
    ui_Panel4 = NULL;
    ui_Voice_Chat_Name = NULL;

}
