// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef UI_MUSIC_SCREEN_H
#define UI_MUSIC_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music_Screen
extern void ui_Music_Screen_screen_init(void);
extern void ui_Music_Screen_screen_destroy(void);
extern void ui_event_Music_Screen(lv_event_t * e);
extern lv_obj_t * ui_Music_Screen;
extern lv_obj_t * ui_TimeLabel;
extern void ui_event_Volume_Panel(lv_event_t * e);
extern lv_obj_t * ui_Volume_Panel;
extern lv_obj_t * ui_uiForVolumePopout;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Vol_Percent;
extern lv_obj_t * ui_SongInformationAndPlayback;
extern lv_obj_t * ui_Song_Name;
extern lv_obj_t * ui_Artist_Name;
extern void ui_event_SongPositionSlider(lv_event_t * e);
extern lv_obj_t * ui_SongPositionSlider;
extern lv_obj_t * ui_CurrentTimeAndTotalTime;
extern lv_obj_t * ui_Current_Time_T1;
extern lv_obj_t * ui_Total_Time_T2;
extern lv_obj_t * ui_SongButtons;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern void ui_event_PlayPauseButton(lv_event_t * e);
extern lv_obj_t * ui_PlayPauseButton;
extern void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
extern lv_obj_t * ui_AlbumCoverContainer;
extern lv_obj_t * ui_SongImage;
extern lv_obj_t * ui_PopoutMenuContainer;
extern void ui_event_PopoutMenuButton(lv_event_t * e);
extern lv_obj_t * ui_PopoutMenuButton;
extern lv_obj_t * ui_Button_Container;
extern lv_obj_t * ui_DiscordIcon;
extern lv_obj_t * ui_SongButtons3;
extern void ui_event_MuteButton2(lv_event_t * e);
extern lv_obj_t * ui_MuteButton2;
extern lv_obj_t * ui_Panel2;
extern void ui_event_DeafenButton2(lv_event_t * e);
extern lv_obj_t * ui_DeafenButton2;
extern lv_obj_t * ui_Panel1;
extern void ui_event_LeaveCallButton2(lv_event_t * e);
extern lv_obj_t * ui_LeaveCallButton2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Voice_Chat_Name;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

