// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef _ESP32S3ENTERTAINMENTDISPLAY_UI_COMP_HOOK_H
#define _ESP32S3ENTERTAINMENTDISPLAY_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Image2_create_hook(lv_obj_t * comp);
void ui_comp_Panel1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
