// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#include "../ui.h"

// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 485);
    lv_obj_set_height(cui_Panel1, 485);
    lv_obj_set_x(cui_Panel1, 1);
    lv_obj_set_y(cui_Panel1, 1);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

