// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#include "../ui.h"

// COMPONENT Image2

lv_obj_t * ui_Image2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_image_create(comp_parent);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 2700
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 2700
    lv_obj_set_x(cui_Image2, -76);
    lv_obj_set_y(cui_Image2, 31);
    lv_obj_set_align(cui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGE2_NUM);
    children[UI_COMP_IMAGE2_IMAGE2] = cui_Image2;
    lv_obj_add_event_cb(cui_Image2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Image2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Image2_create_hook(cui_Image2);
    return cui_Image2;
}

