// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: ESP32S3EntertainmentDisplay

#ifndef _UI_COMP_IMAGE2_H
#define _UI_COMP_IMAGE2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Image2
#define UI_COMP_IMAGE2_IMAGE2 0
#define _UI_COMP_IMAGE2_NUM 1
lv_obj_t * ui_Image2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
